/**:
  ros__parameters:
    # Path downsample spacing (meters)
    waypoint_distance: 0.5
    # Arrival distance to advance to next waypoint (meters)
    arrival_threshold: 0.5
    # Lookahead distance (meters)
    lookahead_dist: 1.0
